name: face_detection_lock_example
description: Example app demonstrating face_detection_lock.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  face_detection_lock:
    path: ../
  # Re-export for direct BLoC usage in the advanced example.
  # ignore: depend_on_referenced_packages
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
