name: face_detection_lock
description: Face detection lock screen widget for Flutter. Unlocks when a face is detected.
version: 0.2.0
repository: https://github.com/FlutterPlaza/face_detection_lock
homepage: https://flutterplaza.com
issue_tracker: https://github.com/FlutterPlaza/face_detection_lock/issues
topics:
  - face-detection
  - security
  - biometric
  - camera
  - lock-screen

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  battery_plus: ^6.0.0
  camera: ^0.11.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  google_mlkit_face_detection: ^0.12.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.0

flutter:
